# Generated by Django 5.1.7 on 2025-05-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
